import React from "react";
import Why from "./homecomponents/Why";
import Nexttrip from "./homecomponents/Nexttrip";
import Tourism from "./homecomponents/Tourism";
import Faq from "./homecomponents/Faq";
import Coupon from "./homecomponents/Coupon";
import Escape from "./homecomponents/Escape";
import Location from "./homecomponents/Location";
import Experience from "./homecomponents/Experience";
import Global from "./homecomponents/Global";
import Hero from "./homecomponents/Hero";
import Blog from "./homecomponents/Blog";
import Newsletter from "./homecomponents/Newsletter";
import Triumph from "./homecomponents/Triumph";
import Testimonials from "./homecomponents/Testimonial";
import Banner from "./homecomponents/Banner";
import Gallery from "./homecomponents/Gallery";
import Design from "./homecomponents/Design";


export const metadata = {
  title: "Triumph Holidays",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <Hero />
      <Why />
      <Nexttrip />
      <Tourism />
      <Escape />
      <Global />
      <Location />
      {/* <Banner /> */}
      <Coupon />
      {/* <Gallery /> */}
      {/* <Design /> */}
      <Blog />

      <Experience />
      <Testimonials />
      <Faq />
      <Newsletter />

      <Triumph />
    </div>
  );
};

export default page;
